services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5174:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host